name: Publish
on:
  - push
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    strategy:
      matrix:
        node-version:
          - "20"
    steps:
      - uses: actions/checkout@v4
      - name: Build and Publish
        if: github.ref == 'refs/heads/main'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm start
